
#          target: mediapc


#      - service:  notify.pushover
#        data:
#          title: Garage Door
#          message: The garage door is open.
#          data:
#            url: https://home-assistant.io/
#            url_title: Home Assistant
#            priority: 2
#            sound: siren
#            expire: 3600
#            retry: 30
#            timestamp: true
#            file:
#              path: /tmp/snapshot_camera_stube.jpg



notify:

  - name: pushover
    platform: pushover
    api_key: !secret pushover_api
    user_key: !secret pushover_user

  # - name: pushover_emergency_alerts_default
  #   platform: group
  #   services:
  #       - service: pushover
  #         data:
  #           title: Garage Door
  #           message: The garage door is open.
  #           data:
  #             url: https://home-assistant.io/
  #             url_title: Home Assistant
  #             priority: 2
  #             sound: siren
  #             expire: 3600
  #             retry: 30
  #             timestamp: true
  #             file:
  #               path: /tmp/snapshot_camera_stube.jpg

#script:
#
#  pushover_test:
#    alias: 'Pushover Test'
#    sequence:
#      - service: camera.snapshot
#        data:
#          entity_id: camera.stube
#          filename: /tmp/snapshot_camera_stube.jpg
#
#      - service:  notify.pushover
#        data:
#          title: Garage Door
#          message: The garage door is open.
#          data:
#            url: https://home-assistant.io/
#            url_title: Home Assistant
#            priority: 2
#            sound: siren
#            expire: 3600
#            retry: 30
#            timestamp: true
#            file:
#              path: /tmp/snapshot_camera_stube.jpg

#alert:
#  test_alert:
#    name: Test Alert Open
#    done_message: Test Alert Closed
#    entity_id: input_boolean.test_switch
#    state: 'on'
#    repeat: 30
#    can_acknowledge: True
#    skip_first: false
#    notifiers:
#      - pushover_emergency_alerts_default



##############################################################################################################################
# INPUT BOOLEAN
##############################################################################################################################

input_boolean:

  test_switch:
    name: Test Switch

###############################################################
# STUBE
###############################################################

  eg_stube_tv:
    name: TV

  eg_stube_soundbar:
    name: Soundbar

###############################################################
# MEDIAROOM
###############################################################

  1st_mediaroom_beamer:
    name: Beamer

###############################################################
# SCHLAFZIMMER
###############################################################

  dach_schlaf_climate:
    name: Klima

  dach_schlaf_tv:
    name: TV

  dach_schlaf_soundbar:
    name: Soundbar


##############################################################################################################################
# INPUT SELECT
##############################################################################################################################

input_select:
  zipatile_siren:
    name: Zipatile Siren
    options:
      - STOP_SOUND
      - EMERGENCY
      - FIRE_ALERT
      - AMBULANCE
      - POLICE_CAR
      - DOOR_CHIME
      - BEEP
    initial: STOP_SOUND

##############################################################################################################################
# BASIC AUTOMATION (Turn OFF and ON and select INPUTS where neccessary)
##############################################################################################################################

automation:

  - alias: Set Zipatile Siren
    trigger:
      platform: state
      entity_id: input_select.zipatile_siren
    action:
      service: mqtt.publish
      data_template:
        topic: !secret zipatile_siren_command
        retain: true
        payload: "{\"command\":\"SET_STATE\",\"value\":\"{{ states('input_select.zipatile_siren') }}\"}"



##############################################################################################################################
# SENSOR ALARM
##############################################################################################################################


  - alias: Send Smoke Emergency Notifications
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.eg_kueche_smokesensor_sensor
          - input_boolean.test_switch
        to: 'on'
    action:
    - service:  notify.pushover
      data_template:
         message: '{{ trigger.from_state.name }} has detected Smoke!'
      data:
        title: Smoke Alarm
        data:
          priority: 2
          sound: siren
          expire: 3600
          retry: 30
          timestamp: true


  - alias: Send Water Emergency Notifications
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.eg_kueche_floodsensor_flood
          - binary_sensor.ug_waschkueche_floodsensor_2_flood
          - input_boolean.test_switch
        to: 'on'
    action:
    - service:  notify.pushover
      data_template:
         message: '{{ trigger.from_state.name }} has detected Water!'
      data:
        title: Water Alarm
        data:
          priority: 2
          sound: siren
          expire: 3600
          retry: 30
          timestamp: true

##############################################################################################################################
# ALARM
##############################################################################################################################

  - alias: Trigger alarm while armed away
    trigger:
      - platform: state
        entity_id: input_boolean.test_switch
        to: 'on'
    condition:
      - condition: state
        entity_id: alarm_control_panel.ha_alarm
        state: armed_away
    action:
      service: alarm_control_panel.alarm_trigger
      entity_id: alarm_control_panel.ha_alarm


  - alias: Send Alarm Notifications
    trigger:
      - platform: state
        entity_id: alarm_control_panel.ha_alarm
        to: 'triggered'
    action:

    - service: camera.snapshot
      data:
        entity_id: camera.stube
        filename: /tmp/snapshot_camera_stube.jpg

    - service:  notify.pushover
      data:
        message: The House Alarm has been triggered
        title: House Alarm
        data:
          priority: 2
          sound: siren
          expire: 3600
          retry: 30
          timestamp: true
          file:
            path: /tmp/snapshot_camera_stube.jpg          


##############################################################################################################################
# PRESENCE
##############################################################################################################################

  - alias: Send Presence Enter Notifications

    trigger:
      - platform: zone
        zone: zone.home
        event: enter
        entity_id: 
          - device_tracker.oeusqgsv_marcel
          - device_tracker.oeusqgsv_jeanette
          
      - platform: zone
        zone: zone.marcel_home_large
        event: enter
        entity_id: 
          - device_tracker.oeusqgsv_marcel
          - device_tracker.oeusqgsv_jeanette    
          
      - platform: zone
        zone: zone.marcel_work
        event: enter
        entity_id: 
          - device_tracker.oeusqgsv_marcel
          - device_tracker.oeusqgsv_jeanette    
          
      - platform: zone
        zone: zone.marcel_work_large
        event: enter
        entity_id: 
          - device_tracker.oeusqgsv_marcel
          - device_tracker.oeusqgsv_jeanette    
  
    action:
      - service:  notify.pushover
        data_template:
           message: '{{ trigger.from_state.name }} has entered the {{ trigger.zone.attributes.friendly_name }} Zone'
        data:
          title: Home Presence Detection

  - alias: Send Presence Leave Notifications

    trigger:
      - platform: zone
        zone: zone.home
        event: leave
        entity_id: 
          - device_tracker.oeusqgsv_marcel
          - device_tracker.oeusqgsv_jeanette
          
      - platform: zone
        zone: zone.marcel_home_large
        event: leave
        entity_id: 
          - device_tracker.oeusqgsv_marcel
          - device_tracker.oeusqgsv_jeanette    
          
      - platform: zone
        zone: zone.marcel_work
        event: leave
        entity_id: 
          - device_tracker.oeusqgsv_marcel
          - device_tracker.oeusqgsv_jeanette    
          
      - platform: zone
        zone: zone.marcel_work_large
        event: leave
        entity_id: 
          - device_tracker.oeusqgsv_marcel
          - device_tracker.oeusqgsv_jeanette    
  
    action:
      - service:  notify.pushover
        data_template:
           message: '{{ trigger.from_state.name }} has left the {{ trigger.zone.attributes.friendly_name }} Zone'
        data:
          title: Home Presence Detection          



  - alias: Send Presence iBeacon Notifications

    trigger:
      - platform: numeric_state
        entity_id: 
          - sensor.marcel_mobile_bt_rp1
          - sensor.marcel_watch_bt_rp1
          - sensor.marcel_car_bt_rp1
          - sensor.marcel_mobile_bt_stube
          - sensor.marcel_watch_bt_stube
          - sensor.marcel_car_bt_stube
          - sensor.marcel_nut_bt_rp1
          - sensor.marcel_nut_bt_stube
        above: 10
    action:
      - service:  notify.pushover
        data_template:
           message: '{{ trigger.from_state.name }} iBeacon Detected'
        data:
          title: iBeacon Detection  


###############################################################
# STUBE
###############################################################

#######################################
# SHIELD POWER Handling/Tracking
#######################################

  - alias: Shield 01 ON Handling
    trigger:
      platform: state
      entity_id: switch.shield_01_power
      to: 'on'
    action:
    - service: input_boolean.turn_on
      entity_id: 
        - input_boolean.eg_stube_tv
        - input_boolean.eg_stube_soundbar

  - alias: Shield 01 OFF Handling
    trigger:
      platform: state
      entity_id: switch.shield_01_power
      to: 'off'
    action:
    - service: input_boolean.turn_off
      entity_id: 
        - input_boolean.eg_stube_tv
        - input_boolean.eg_stube_soundbar

#######################################
# SHIELD FULL SCREEN VIDEO LIGHT CONTROL
#######################################

  - alias: Shield 01 Video Playback ON Handling
    trigger:
      platform: state
      entity_id: sensor.shield_01_video_playback
      to: 'on'
    action:
    - service: homeassistant.turn_off
      entity_id: 
        - switch.eg_stube_licht_1_switch

  - alias: Shield 01 Video Playback OFF Handling
    trigger:
      platform: state
      entity_id: sensor.shield_01_video_playback
      to: 'off'
    action:
    - service: homeassistant.turn_on
      entity_id: 
        - switch.eg_stube_licht_1_switch

#######################################
# TV
#######################################

  - alias: Turn Stube TV ON
    trigger:
      platform: state
      entity_id: input_boolean.eg_stube_tv
      to: 'on'
    action:
    - service: mqtt.publish
      data:
        topic: "/rpi_support/mediapc01/sendir/samsung"
        payload: "KEY_BLUE"   
    - service: mqtt.publish
      data:
        topic: "/rpi_support/mediapc01/sendir/samsung"
        payload: "BTN_TOP" 

  - alias: Turn Stube TV OFF
    trigger:
      platform: state
      entity_id: input_boolean.eg_stube_tv
      to: 'off'
    action:
    - service: mqtt.publish
      data:
        topic: "/rpi_support/mediapc01/sendir/samsung"
        payload: "KEY_GREEN"   

#######################################
# SOUNDBAR
#######################################

  - alias: Turn Stube Soundbar ON
    trigger:
      platform: state
      entity_id: input_boolean.eg_stube_soundbar
      to: 'on'
    action:
    - service: mqtt.publish
      data:
        topic: "/rpi_support/mediapc01/sendir/soundbar"
        payload: "BTN_TOUCH"   
    - service: mqtt.publish
      data:
        topic: "/rpi_support/mediapc01/sendir/soundbar"
        payload: "BTN_TOP" 

  - alias: Turn Stube Soundbar OFF
    trigger:
      platform: state
      entity_id: input_boolean.eg_stube_soundbar
      to: 'off'
    action:
    - service: mqtt.publish
      data:
        topic: "/rpi_support/mediapc01/sendir/soundbar"
        payload: "BTN_TR" 

###############################################################
# MEDIAROOM
###############################################################

#######################################
# SHIELD POWER Handling/Tracking
#######################################

  - alias: Shield 02 ON Handling
    trigger:
      platform: state
      entity_id: switch.shield_02_power
      to: 'on'
    action:
    - service: input_boolean.turn_on
      entity_id: 
        - input_boolean.1st_mediaroom_beamer
    - service: media_player.turn_on
      data:
        entity_id: media_player.mediaroom_avr_player
    - service: media_player.select_source
      data:
        entity_id: media_player.mediaroom_avr_player
        source: "BD"

  - alias: Shield 02 OFF Handling
    trigger:
      platform: state
      entity_id: switch.shield_02_power
      to: 'off'
    action:
    - service: input_boolean.turn_off
      entity_id: 
        - input_boolean.1st_mediaroom_beamer
    - service: media_player.turn_off
      data:
        entity_id: media_player.mediaroom_avr_player

#######################################
# BEAMER
#######################################

  - alias: Turn Mediaroom Beamer ON
    trigger:
      platform: state
      entity_id: input_boolean.1st_mediaroom_beamer
      to: 'on'
    action:
    - service: mqtt.publish
      data:
        topic: "/rpi_support/mediapc02/sendserial"
        payload: "pow=on"   

  - alias: Turn Mediaroom Beamer OFF
    trigger:
      platform: state
      entity_id: input_boolean.1st_mediaroom_beamer
      to: 'off'
    action:
    - service: mqtt.publish
      data:
        topic: "/rpi_support/mediapc02/sendserial"
        payload: "pow=off"   

#######################################
# SHIELD FULL SCREEN VIDEO LIGHT CONTROL
#######################################

  - alias: Shield 02 Video Playback ON Handling
    trigger:
      platform: state
      entity_id: sensor.shield_02_video_playback
      to: 'on'
    action:
      service: light.turn_off
      entity_id: light.1st_mediaroom_licht_level

  - alias: Shield 02 Video Playback OFF Handling
    trigger:
      platform: state
      entity_id: sensor.shield_02_video_playback
      to: 'off'
    action:
      service: light.turn_on
      data:
        entity_id: light.1st_mediaroom_licht_level
        brightness: 255

###############################################################
# SCHLAFZIMMER
###############################################################

#######################################
# SHIELD POWER Handling/Tracking
#######################################

  - alias: Shield 03 ON Handling
    trigger:
      platform: state
      entity_id: switch.shield_03_power
      to: 'on'
    action:
    - service: input_boolean.turn_on
      entity_id: 
        - input_boolean.dach_schlaf_tv
        - input_boolean.dach_schlaf_soundbar

  - alias: Shield 03 OFF Handling
    trigger:
      platform: state
      entity_id: switch.shield_03_power
      to: 'off'
    action:
    - service: input_boolean.turn_off
      entity_id: 
        - input_boolean.dach_schlaf_tv
        - input_boolean.dach_schlaf_soundbar

#######################################
# TV
#######################################

  - alias: Turn Schlafzimmer TV ON
    trigger:
      platform: state
      entity_id: input_boolean.dach_schlaf_tv
      to: 'on'
    action:
    - service: mqtt.publish
      data:
        topic: "/rpi_support/mediapc03/sendir/samsung"
        payload: "KEY_BLUE"   
    - service: mqtt.publish
      data:
        topic: "/rpi_support/mediapc03/sendir/samsung"
        payload: "BTN_TOP2" 

  - alias: Turn Schlafzimmer TV OFF
    trigger:
      platform: state
      entity_id: input_boolean.dach_schlaf_tv
      to: 'off'
    action:
    - service: mqtt.publish
      data:
        topic: "/rpi_support/mediapc03/sendir/samsung"
        payload: "KEY_GREEN"   

#######################################
# SOUNDBAR
#######################################

  - alias: Turn Schlafzimmer Soundbar ON
    trigger:
      platform: state
      entity_id: input_boolean.dach_schlaf_soundbar
      to: 'on'
    action:
    - service: mqtt.publish
      data:
        topic: "/rpi_support/mediapc03/sendir/soundbar"
        payload: "BTN_TOUCH"   
    - service: mqtt.publish
      data:
        topic: "/rpi_support/mediapc03/sendir/soundbar"
        payload: "BTN_TOP2" 

  - alias: Turn Schlafzimmer Soundbar OFF
    trigger:
      platform: state
      entity_id: input_boolean.dach_schlaf_soundbar
      to: 'off'
    action:
    - service: mqtt.publish
      data:
        topic: "/rpi_support/mediapc03/sendir/soundbar"
        payload: "BTN_TR" 

#######################################
# CLIMATE
#######################################

  - alias: Turn Schlafzimmer Climate ON
    trigger:
      platform: state
      entity_id: input_boolean.dach_schlaf_climate
      to: 'on'
    action:
    - service: mqtt.publish
      data:
        topic: "/rpi_support/mediapc03/sendir/climate"
        payload: "KEY_BLUE"   

  - alias: Turn Schlafzimmer Climate OFF
    trigger:
      platform: state
      entity_id: input_boolean.dach_schlaf_climate
      to: 'off'
    action:
    - service: mqtt.publish
      data:
        topic: "/rpi_support/mediapc03/sendir/climate"
        payload: "KEY_GREEN" 
